version: '2'
services:

  # Java App with Mongo DB

  db:
      image: mongo
      volumes:
        - "/data/mongodb:/data/db"
      restart: always

  tracker:
      depends_on:
        - db
      image: es.flaviojmend/fitbit-tracker:1.0.0
      links:
        - db
      ports:
        - "80:80"
      restart: always