version: '3'
services:

  db:
      image: mongo
      container_name: db
      ports:
        - '27017:27017'
      volumes:
        - "/data/mongodb:/data/db"
      restart: always
      networks:
        - default

  tracker:

      image: fitbit-tracker
      container_name: fitbit-tracker
      volumes:
        - "/etc/ssl/certs:/etc/ssl/certs:ro"
      links:
        - db
      external_links:
        - config-server
      depends_on:
        - db
      ports:
        - 8445:8445
      restart: always
      networks:
        - owlabs
      environment:
        - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
        - SPRING_CLOUD_CONFIG_ENABLED=true
        - SPRING_PROFILES_ACTIVE=prod

networks:
  owlabs: