version: '3'
services:

  # Java App with Mongo DB

  db:
      image: mongo

      container_name: db

      ports:
            - '27017:27017'

      volumes:
        - "/data/mongodb:/data/db"

      restart: always

  tracker:

      depends_on:
        - db

      image: fitbit-tracker

      container_name: fitbit-tracker

      volumes:
        - "/etc/ssl/certs:/etc/ssl/certs:ro"

      links:
        - db

      ports:
        - "8443:8443"

      restart: always